# Generated by Django 6.0.5 on 2026-06-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
