# Generated by Django 6.0.5 on 2026-06-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_customer_store_custo_last_na_e6a359_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customer",
            new_name="store_custo_last_na_2e448d_idx",
            old_name="store_custo_last_na_e6a359_idx",
        ),
        migrations.AlterModelTable(
            name="customer",
            table=None,
        ),
    ]
